<?php
/** @package Napoli::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("ProductoMap.php");

/**
 * ProductoDAO provides object-oriented access to the producto table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Napoli::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class ProductoDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $CodProveedor;

	/** @var string */
	public $Descripcion;

	/** @var int */
	public $UnidadMedida;

	/** @var int */
	public $Uxb;

	/** @var int */
	public $Rubro;


	/**
	 * Returns the foreign object based on the value of Rubro
	 * @return Rubro
	 */
	public function GetRubro()
	{
		return $this->_phreezer->GetManyToOne($this, "producto_ibfk_1");
	}


}
?>